### ISSUE TITLE
How to Show only images and not video

### ISSUE THREAD

**Issue by sakshimidha** [jsanahuja/jquery.instagramFeed#135] opened 2021-04-06 06:40 UTC
I need to display only images from the Instagram gallery and not videos.
Is there any way, we can do that?

Thanks,
Sakshi

**Comment by laryn** [comment] 2021-04-28 14:18
Duplicate of https://github.com/jsanahuja/jquery.instagramFeed/issues/129

**Closed** 2021-04-30 18:31 UTC
