### ISSUE TITLE
number of pics - load more...

### ISSUE THREAD

**Issue by mmjaeger** [jsanahuja/jquery.instagramFeed#75] opened 2020-07-18 20:53 UTC
Hello
no matter what number I use I only get 12 pictures - I put in 100, still only get 12 pictures - was wondering what is going on.

how difficult would it be to e.g. show an initial 9 picture and give the user/visitor the option to load more pictures?

Thanks in advance for your input.

**Comment by jsanahuja** [comment] 2020-07-19 18:31
Duplicate of #31

**Closed** 2020-07-25 01:14 UTC
Labels: 05 ISSUE: Duplicate
