### ISSUE TITLE
It stopped working for me

### ISSUE THREAD

**Issue by rafaelvinicius** [jsanahuja/jquery.instagramFeed#25] opened 2019-08-22 20:30 UTC
Only Instagram images appear searching for TAG. By username shows error.

In the example it is also not working, and displays the same error: 

Uncaught TypeError: Cannot read property '0' of undefined

![Screenshot_1](https://user-images.githubusercontent.com/3720793/63547334-4e8d4b80-c502-11e9-9328-22a2d4ca8a64.png)

**Comment by jsanahuja** [comment] 2019-08-22 22:57
Please provide the code and version you are using

**Comment by omeercoskun** [comment] 2019-08-23 05:38
Same problem. From data.entry_data, ProfilePage[0] should return and LoginAndSignupPage returns.
Sometimes return ProfilPage, sometimes return LoginAndSignupPage

![inst](https://user-images.githubusercontent.com/5605738/63569223-2a248400-c581-11e9-82b8-41cde7c9cd49.PNG)

**Comment by rafaelvinicius** [comment] 2019-08-23 13:10
> Please provide the code and version you are using

@version 1.2.0

```
<script>
	(function($){
		$(window).on('load', function(){                
			$.instagramFeed({
				'username': 'rafaelvinicius',
				//'tag': 'paradise',
				'container': "#FotosInstagram",
				'display_profile': false,
				'display_biography': false,
				'display_gallery': true,
				'get_data': false,
				'callback': null,
				'styling': false,
				'items': 12,
				'items_per_row': 6,
				'margin': 20,
				'image_size': 240
			});
		});
	})(jQuery);
</script>
```

Today it went back to work and without any error message.
On your demo page has also returned to work.

**Comment by omeercoskun** [comment] 2019-08-23 13:17
Your online demo page same error in my server. And There are no problems accessing instagram.
![inst2](https://user-images.githubusercontent.com/5605738/63595228-1567e080-c5c1-11e9-9363-ab27880e5e76.PNG)

**Comment by jsanahuja** [comment] 2019-08-23 16:06
@rafaelvinicius your code works perfectly fine on my side: https://www.sowecms.com/demos/jquery.instagramFeed/test_issue_25.html
Changed the user but works perfectly fine with yours.

@omeercoskun looks like the http request is giving an unexpected response. Can you please show the network tab?

**Comment by iccunha** [comment] 2019-08-23 20:45
Lately, instagram has introduced a rate limitation that redirects to the login and signup page when fetching the user page, just change the ip / proxy

**Comment by rafaelvinicius** [comment] 2019-08-23 21:47
@jsanahuja, thanks for the quick response!
As I said in the comment above, this morning it worked for me again. I spent the whole day working on the project, and at no time did Instagram make mistakes.

@iccunha
Yesterday I auditioned for the LTE network, the office network and my home network, on all these different connections Instagram was not working.
Can you tell us what is the limit imposed by Instagram?

**Comment by iccunha** [comment] 2019-08-23 21:50
@rafaelvinicius I dont know yet, I m doing tests

**Comment by jsanahuja** [comment] 2019-08-23 21:57
@iccunha you are right
![image](https://user-images.githubusercontent.com/16489902/63625128-f2f4b800-c5fe-11e9-91ea-0eaa41f9d03b.png)

The fetch is made client-side so the impact of this limitation is the same you would feel navigating directly over the instagram website.

I wasn't able to reproduce this refreshing the demo page as fast as I could. Had to make about 15 requests (I ran the 1st code example 15 times in a row) to get the first 301 and was at the very end.

**Comment by jsanahuja** [comment] 2019-08-24 15:40
I'm closing this issue as long as the limitation has nothing to do with the library.
Thank you all!

**Closed by jsanahuja** 2019-08-24 15:40 UTC

**Comment by paoga87** [comment] 2020-06-06 03:03
fwiw - I was having this issue working locally. I realized I was on VPN and after disconnecting from VPN, the feed started working again for me.
